name: proteqme
description: "ProteqMe — offline-first voice-activated SOS for Sri Lanka."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  permission_handler: ^12.0.1
  url_launcher: ^6.3.2
  geolocator: ^14.0.2
  google_fonts: ^6.3.2
  sqflite: ^2.4.2
  path: ^1.9.1
  local_auth: ^2.3.0
  connectivity_plus: ^6.1.4
  nearby_connections: ^4.3.0
  phone_state: ^3.0.1
  http: ^1.2.2
  flutter_contacts: ^1.1.9+2
  flutter_secure_storage: ^9.2.4
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/branding/

flutter_launcher_icons:
  android: true
  image_path: assets/branding/proteqher_logo.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/branding/proteqher_logo.png
